import fs from 'node:fs';import assert from 'node:assert/strict';
import {normalise,findServices,nextWaste,swissToday,makeICS} from '../wp-content/plugins/oberhub-core/assets/app.js';
const data=JSON.parse(fs.readFileSync(new URL('../data/seed.json',import.meta.url)));const results=[];const test=(name,fn)=>{try{fn();results.push({name,passed:true});console.log('PASS '+name)}catch(e){results.push({name,passed:false,detail:e.message});console.log('FAIL '+name+' '+e.message)}};
for(const [query,lang,id] of [['Wohnsitzbestätigung','de','23627'],['wo anmelden','de','23620'],['переезд','ru','23620'],['куда сообщить адрес','ru','23620'],['сміття Montlingen','uk','24176'],['garbage Kriessern','en','24176'],['school registration','en','school'],['фонарь не работает','ru','lighting'],['Steuererklärung','de','23986']])test('Search '+query,()=>assert.equal(findServices(data,query,lang)[0]?.id,id));
test('Unknown question returns no invented result',()=>assert.equal(findServices(data,'zyxqv987zzblorf','en').length,0));
test('Unicode and Swiss orthography',()=>assert.equal(normalise('  STRAßE   Zürich '),'strasse zurich'));
const w=id=>data.waste.find(w=>w.id===id);
test('Montlingen cardboard next Wednesday',()=>assert.equal(nextWaste(w('karton'),'montlingen','2026-10-01'),'2026-10-07'));
test('Kriessern household waste Monday',()=>assert.equal(nextWaste(w('kehricht'),'kriessern','2026-10-01'),'2026-10-05'));
test('Montlingen paper 7 November',()=>assert.equal(nextWaste(w('papier'),'montlingen','2026-10-01'),'2026-11-07'));
test('Kobelwald mountain-area paper 2 November',()=>assert.equal(nextWaste(w('papier'),'kobelwald','2026-10-01'),'2026-11-02'));
test('No invented green collection date',()=>assert.equal(nextWaste(w('gruen'),'montlingen','2026-10-01'),null));
test('2026 waste data never reused for 2027',()=>assert.equal(nextWaste(w('kehricht'),'montlingen','2027-01-01'),null));
test('Swiss local-date rollover',()=>assert.equal(swissToday(new Date('2026-10-01T23:00:00Z')),'2026-10-02'));
const ics=makeICS(data.events,'uk');
test('ICS UTF-8 folding <=75 octets',()=>assert.ok(ics.split('\r\n').every(x=>Buffer.byteLength(x)<=75)));
test('ICS inclusive event end exported exclusive',()=>assert.ok(ics.includes('DTEND;VALUE=DATE:20261005')));
test('ICS mandatory delimiters and CRLF',()=>assert.ok(ics.startsWith('BEGIN:VCALENDAR\r\n')&&ics.endsWith('END:VCALENDAR\r\n')));
test('Provenance references consistent',()=>{const sources=new Set(data.sources.map(s=>s.source_id));for(const k of ['services','contacts','events','places','waste'])for(const record of data[k])assert.ok(sources.has(record.source_id),k+'/'+record.id)});
test('Four-language service summaries complete',()=>{for(const service of data.services)for(const l of ['de','en','ru','uk'])assert.ok(service.title[l]&&service.description_short[l])});
fs.writeFileSync(new URL('./results/unit.json',import.meta.url),JSON.stringify(results,null,2));if(results.some(x=>!x.passed))process.exit(1);
