<?php
namespace OberHub;
final class Frontend {
    public static function boot(): void {
        add_action('init',[self::class,'rewrite']);add_filter('query_vars',fn($v)=>array_merge($v,['oh_lang','oh_path']));
        add_filter('template_include',function($t){return self::is_hub() ? get_stylesheet_directory().'/hub.php' : $t;},99);
        add_action('template_redirect',[self::class,'redirect']);
        add_action('wp_enqueue_scripts',[self::class,'assets']);add_action('wp_head',[self::class,'seo'],1);
        add_filter('pre_get_document_title',fn($t)=>self::is_hub() ? self::title().' · Oberriet Hub' : $t);
        add_shortcode('oberhub',[self::class,'render']);
        add_filter('script_loader_tag',function($tag,$handle){return $handle==='oberhub-app' ? preg_replace('/<script(?:\s+type=[\"\'][^\"\']*[\"\'])?\s*/','<script type="module" ',$tag,1) : $tag;},10,2);
        add_filter('wp_robots',function($r){if (self::is_hub() && (!self::operator_ready() || !self::valid())) { $r['noindex']=true;$r['nofollow']=true;unset($r['max-image-preview']); }return $r;});
        add_filter('robots_txt',function($t){return $t."\nDisallow: /wp-admin/\nDisallow: /wp-json/\nSitemap: ".home_url('/oh-sitemap.xml')."\n";});
    }
    public static function rewrite(): void { add_rewrite_rule('^(de|en|ru|uk)/?(.*)$','index.php?oh_lang=$matches[1]&oh_path=$matches[2]','top');add_rewrite_rule('^oh-sitemap\.xml$','index.php?oh_path=sitemap','top'); }
    public static function lang(): string { $l=get_query_var('oh_lang');return in_array($l,['de','en','ru','uk'],true) ? $l : 'de'; }
    public static function path(): string { return trim((string)get_query_var('oh_path'),'/'); }
    public static function is_hub(): bool { return (bool)get_query_var('oh_lang') || self::path()==='sitemap' || (is_front_page() && self::path()===''); }
    public static function ui(): array { static $u; if (!$u) { $u=json_decode(file_get_contents(OBERHUB_DIR.'/ui.json'),true); }return $u[self::lang()]; }
    public static function t(string $key): string { return self::ui()[$key] ?? $key; }
    public static function url(string $path='',?string $lang=null): string { return home_url('/'.($lang ?: self::lang()).'/'.($path ? trim($path,'/').'/' : '')); }
    public static function title(): string {
        $p=explode('/',self::path()); if (self::path()==='') { return self::t('hero'); }
        if (($p[0] ?? '')==='services' && isset($p[1])) { foreach (records('service') as $s) { if ($s['id']===$p[1]) { return $s['title'][self::lang()]; } } }
        if (in_array($p[0] ?? '',['contacts','organizations'],true) && isset($p[1])) { foreach(records($p[0]==='contacts'?'contact':'organization') as $r) { if($r['id']===$p[1]) { return is_array($r['title']) ? $r['title'][self::lang()] : $r['title']; } } }
        if (($p[0] ?? '')==='places') { return ucfirst($p[1] ?? ''); }
        if (($p[0] ?? '')==='topics') { return self::t($p[1] ?? ''); }
        return self::t($p[0]);
    }
    public static function operator_ready(): bool { $o=get_option('oh_operator',[]); return !empty($o['operator']) && !empty($o['address']) && is_email($o['email'] ?? '') && !empty($o['hosting_provider']) && !empty($o['hosting_country']); }
    public static function valid(): bool {
        $p=explode('/',self::path());if (self::path()==='' || in_array(self::path(),['services','search','calendar','waste','ask','contact','about','sources','privacy','imprint','accessibility','organizations','contacts','faq'],true)) { return true; }
        if (count($p)!==2) { return false; }
        if ($p[0]==='places') { return in_array($p[1],['oberriet','montlingen','kriessern','eichenwies','kobelwald'],true); }
        if ($p[0]==='topics') { return in_array($p[1],['administration','everyday-life','health-social','education-family','jobs-business','culture-leisure'],true); }
        if ($p[0]==='services') { return in_array($p[1],array_column(records('service'),'id'),true); }
        if (in_array($p[0],['contacts','organizations'],true)) { return in_array($p[1],array_column(records($p[0]==='contacts'?'contact':'organization'),'id'),true); } return false;
    }
    public static function redirect(): void {
        if (!self::is_hub()) { return; }
        remove_action('wp_head','rel_canonical');if(class_exists(ImportQueue::class)&&ImportQueue::active()){status_header(503);nocache_headers();header('Retry-After: 300');return;}
        if (self::path()==='sitemap') {
            header('Content-Type: application/xml; charset=utf-8');echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
            foreach (['de','en','ru','uk'] as $l) { foreach (array_merge(['','services','organizations','contacts','faq','search','topics/administration','topics/everyday-life','topics/health-social','topics/education-family','topics/jobs-business','topics/culture-leisure','calendar','waste','ask','contact','about','sources','privacy','imprint','accessibility'],array_map(fn($x)=>'places/'.$x,['oberriet','montlingen','kriessern','eichenwies','kobelwald']),array_map(fn($s)=>'services/'.$s['id'],records('service'))) as $p) { echo '<url><loc>'.esc_url(self::url($p,$l)).'</loc></url>'; } }echo '</urlset>';exit;
        }
        if (!self::valid()) { status_header(404);nocache_headers(); }
        else { status_header(200);Analytics::count('page_view',self::lang()); if (self::path()==='waste') { Analytics::count('waste_search'); } }
    }
    public static function assets(): void {
        if (!self::is_hub()) { return; }
        remove_action('wp_head','print_emoji_detection_script',7);remove_action('wp_print_styles','print_emoji_styles');remove_action('wp_footer','wp_print_speculation_rules');
        wp_enqueue_style('oberhub',OBERHUB_URL.'assets/app.css',[], '0.2.1');wp_enqueue_script('oberhub-app',OBERHUB_URL.'assets/app.js',[], '0.2.1',true);
    }
    public static function seo(): void {
        if (!self::is_hub()) { return; }
        $url=self::url(self::path());$description=self::title().' — '.self::t('intro').' '.self::t('independent');
        $sp=explode('/',self::path());if (($sp[0] ?? '')==='services' && isset($sp[1])) { foreach (records('service') as $s) { if ($s['id']===$sp[1]) { $description=$s['description_short'][self::lang()]; } } }
        echo '<meta name="description" content="'.esc_attr($description).'"><link rel="canonical" href="'.esc_url($url).'"><link rel="icon" type="image/svg+xml" href="'.esc_url(OBERHUB_URL.'assets/mark.svg').'">';
        foreach (['de'=>'de-CH','en'=>'en','ru'=>'ru','uk'=>'uk'] as $l=>$tag) { echo '<link rel="alternate" hreflang="'.esc_attr($tag).'" href="'.esc_url(self::url(self::path(),$l)).'">'; }
        echo '<link rel="alternate" hreflang="x-default" href="'.esc_url(self::url(self::path(),'de')).'"><meta property="og:title" content="'.esc_attr(self::title().' · Oberriet Hub').'"><meta property="og:description" content="'.esc_attr($description).'"><meta property="og:url" content="'.esc_url($url).'"><meta property="og:type" content="website">';
        $graph=[['@type'=>'WebSite','@id'=>home_url('/#website'),'name'=>'Oberriet Hub','url'=>home_url('/'),'inLanguage'=>['de-CH','en','ru','uk'],'potentialAction'=>['@type'=>'SearchAction','target'=>['@type'=>'EntryPoint','urlTemplate'=>self::url('search').'?q={search_term_string}'],'query-input'=>'required name=search_term_string']],['@type'=>'Organization','@id'=>home_url('/#organization'),'name'=>'Oberriet Hub','url'=>home_url('/')]];
        $p=explode('/',self::path());$graph[]=['@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>self::t('home'),'item'=>self::url()],['@type'=>'ListItem','position'=>2,'name'=>self::title(),'item'=>$url]]];
        if ($p[0]==='places') { $graph[]=['@type'=>'Place','name'=>ucfirst($p[1] ?? ''),'url'=>$url]; }
        if ($p[0]==='services' && isset($p[1])) { foreach (records('service') as $s) { if ($s['id']===$p[1] && ($s['source_trust_level'] ?? '')==='A' && preg_match('/Gemeinde|Einwohneramt|Steueramt|Amt für|Kassieramt|Bauamt|AHV-Zweigstelle|Soziale Dienste|Zivilstandsamt|Grundbuchamt|Betreibungsamt/',$s['authority']) && $s['id']!=='lighting') { $graph[]=['@type'=>'GovernmentService','name'=>$s['title'][self::lang()],'description'=>$s['description_short'][self::lang()],'url'=>$url,'provider'=>['@type'=>'GovernmentOrganization','name'=>$s['authority']],'serviceUrl'=>$s['official_url']]; } } }
        if (self::path()==='calendar' || self::path()==='') { foreach (records('event') as $e) { if (($e['end_date'] ?? $e['date']) < wp_date('Y-m-d')) { continue; }$graph[]=['@type'=>'Event','name'=>$e['title'][self::lang()],'startDate'=>$e['date'],'endDate'=>$e['end_date'] ?? $e['date'],'url'=>$e['source_url'],'location'=>['@type'=>'Place','name'=>$e['location']],'description'=>$e['description'][self::lang()],'eventStatus'=>'https://schema.org/EventScheduled']; } }
        // Static JSON only. No AI or resident text is emitted in structured metadata.
        echo '<script type="application/ld+json">'.wp_json_encode(['@context'=>'https://schema.org','@graph'=>$graph],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE).'</script>';
    }
    public static function source(array $s): string {
        $source=array_column(records('source'),null,'source_id')[$s['source_id'] ?? ''] ?? [];
        $date=$s['source_checked_at'] ?? $source['last_checked'] ?? '';$needs=($source['review_status'] ?? 'checked')!=='checked' || ($date && strtotime($date.' +'.($source['ttl_days'] ?? 30).' days')<time()) || (self::lang()!=='de' && ($s['translation_status'][self::lang()] ?? '')==='stale');
        return '<div class="provenance"><a href="'.esc_url($s['source_url'] ?? $source['source_url'] ?? '#').'" rel="noopener">'.esc_html(self::t('source')).' ↗</a><span>'.esc_html(self::t('checked').' '.$date).'</span>'.($needs ? '<span class="warning">'.esc_html(self::t('needsreview')).'</span>' : '').'</div>';
    }
    public static function card(array $s): string {
        $l=self::lang();return '<article class="service-card" data-topic="'.esc_attr($s['topic']).'"><div class="eyebrow">'.esc_html(self::t($s['topic'])).'</div><h3><a href="'.esc_url(self::url('services/'.$s['id'])).'">'.esc_html($s['title'][$l]).'</a></h3><p>'.esc_html($s['description_short'][$l]).'</p><div class="card-bottom"><span>'.esc_html($s['authority']).'</span><a class="arrow" aria-label="'.esc_attr(self::t('details').' — '.$s['title'][$l]).'" href="'.esc_url(self::url('services/'.$s['id'])).'">↗</a></div>'.self::source($s).'</article>';
    }
    public static function select(string $id,string $label,array $values): string { $h='<label class="field" for="'.esc_attr($id).'">'.esc_html($label).'<select id="'.esc_attr($id).'">'; foreach ($values as $v=>$name) { $h.='<option value="'.esc_attr($v).'">'.esc_html($name).'</option>'; }return $h.'</select></label>'; }
    public static function localities(): array { return ['all'=>self::t('all'),'oberriet'=>'Oberriet','montlingen'=>'Montlingen','kriessern'=>'Kriessern','eichenwies'=>'Eichenwies','kobelwald'=>'Kobelwald']; }
    public static function searchform(): string { return '<form id="search-form" role="search"><label class="sr-only" for="query">'.esc_html(self::t('search')).'</label><div class="searchbox"><span aria-hidden="true">⌕</span><input type="search" id="query" autocomplete="off" maxlength="300" placeholder="'.esc_attr(self::t('placeholder')).'" aria-controls="search-results"><button type="submit">'.esc_html(self::t('search')).' <span aria-hidden="true">→</span></button></div></form><div id="search-results" class="search-results" aria-live="polite"></div>'; }
    public static function render(): string {
        $u=self::ui();if(class_exists(ImportQueue::class)&&ImportQueue::active()){return '<main class="wrap prose"><h1>'.esc_html(self::t('setuppending')).'</h1><p>'.esc_html(self::t('setupmessage')).'</p></main>';}$d=dataset(false);$l=self::lang();$path=self::path();$parts=explode('/',$path);$active=$parts[0];$valid=self::valid();ob_start();
        ?><a class="skip" href="#main"><?php echo esc_html($u['skip']); ?></a><div id="oberhub-app" data-lang="<?php echo esc_attr($l); ?>" data-path="<?php echo esc_attr($path); ?>" data-api="<?php echo esc_url(rest_url('oberhub/v1')); ?>" data-base="<?php echo esc_url(home_url('/')); ?>" data-assets="<?php echo esc_url(OBERHUB_URL.'assets/'); ?>">
        <div class="topline"><div class="wrap"><span><?php echo esc_html($u['independent']); ?></span><span>Oberriet · Montlingen · Kriessern · Eichenwies · Kobelwald</span></div></div>
        <header class="header wrap"><a class="brand" href="<?php echo esc_url(self::url()); ?>"><img src="<?php echo esc_url(OBERHUB_URL.'assets/mark.svg'); ?>" width="44" height="44" alt=""><span>oberriet<span class="brand-light">hub</span><small><?php echo esc_html($u['knowledge']); ?></small></span></a><nav class="mainnav" aria-label="<?php echo esc_attr($u['services']); ?>"><?php foreach (['services','calendar','waste','ask'] as $p) { ?><a <?php if($active===$p) { echo 'aria-current="page"'; } ?> href="<?php echo esc_url(self::url($p)); ?>"><?php echo esc_html($u[$p]); ?></a><?php } ?></nav><nav class="languages" aria-label="<?php echo esc_attr($u['language']); ?>"><?php foreach (['de','en','ru','uk'] as $tag) { ?><a lang="<?php echo esc_attr($tag); ?>" <?php if($l===$tag) { echo 'aria-current="true"'; } ?> href="<?php echo esc_url(self::url($path,$tag)); ?>"><?php echo esc_html(strtoupper($tag)); ?></a><?php } ?></nav></header>
        <main id="main" class="wrap" tabindex="-1">
        <?php if (!$valid) { ?><section class="pagehead"><h1><?php echo esc_html($u['notfound']); ?></h1><a class="button" href="<?php echo esc_url(self::url()); ?>"><?php echo esc_html($u['home']); ?></a></section><?php } else {
        if ($path==='') { ?><section class="hero"><div class="hero-copy"><p class="eyebrow"><?php echo esc_html($u['fivevillages']); ?></p><h1><?php echo esc_html($u['hero']); ?></h1><p class="lead"><?php echo esc_html($u['intro']); ?></p><?php echo self::searchform(); ?><div class="quicklinks"><?php foreach (['23620','23627','24176','school','23986','rav'] as $id) { $s=array_column($d['services'],null,'id')[$id]; ?><a href="<?php echo esc_url(self::url('services/'.$id)); ?>"><?php echo esc_html($s['title'][$l]); ?> ↗</a><?php } ?></div><p class="quiet"><?php echo esc_html($u['free']); ?></p></div><div class="hero-aside"><span class="small-index">01 / 05</span><svg class="village-art" viewBox="0 0 270 200" aria-hidden="true"><path d="M0 150L65 66L109 120L179 35L270 147V200H0Z" fill="#a8bfa6"/><path d="M0 164L101 90L160 147L231 81L270 147V200H0Z" fill="#719682"/><path d="M30 200C102 115 183 209 246 131" stroke="#e9e4c9" stroke-width="14" fill="none"/><g fill="#f6f5f0"><circle cx="64" cy="135" r="5"/><circle cx="111" cy="156" r="5"/><circle cx="159" cy="143" r="5"/><circle cx="194" cy="160" r="5"/><circle cx="227" cy="118" r="5"/></g></svg><h2><?php echo esc_html($u['locality']); ?></h2><?php echo self::select('locality',$u['locality'],self::localities()); ?><a id="place-link" href="<?php echo esc_url(self::url('places/oberriet')); ?>"><?php echo esc_html($u['details']); ?> →</a><p><?php echo esc_html($u['quality']); ?></p></div></section>
        <section class="section"><div class="section-title"><h2><?php echo esc_html($u['popular']); ?></h2><a href="<?php echo esc_url(self::url('services')); ?>"><?php echo esc_html($u['viewall']); ?> →</a></div><div class="cards"><?php foreach (['23620','23627','school'] as $id) { echo self::card(array_column($d['services'],null,'id')[$id]); } ?></div></section><div class="two-columns"><section class="section panel"><h2><?php echo esc_html($u['upcoming']); ?></h2><div id="event-list"></div><a href="<?php echo esc_url(self::url('calendar')); ?>"><?php echo esc_html($u['calendar']); ?> →</a></section><section class="section panel"><h2><?php echo esc_html($u['nextwaste']); ?></h2><div id="waste-list"></div><a href="<?php echo esc_url(self::url('waste')); ?>"><?php echo esc_html($u['waste']); ?> →</a></section></div>
        <?php } else { ?><nav class="breadcrumbs" aria-label="<?php echo esc_attr($u['breadcrumb']); ?>"><a href="<?php echo esc_url(self::url()); ?>"><?php echo esc_html($u['home']); ?></a><span>/</span><span><?php echo esc_html(self::title()); ?></span></nav><section class="pagehead"><p class="eyebrow"><?php echo esc_html($u['independent']); ?></p><h1><?php echo esc_html(self::title()); ?></h1></section><?php
        switch ($active) {
            case 'search': echo self::searchform();break;
            case 'services':
                if (isset($parts[1])) { $s=array_column($d['services'],null,'id')[$parts[1]]; ?>
                <div class="detail-layout"><article class="prose"><p class="lead"><?php echo esc_html($s['description_full'][$l]); ?></p><h2><?php echo esc_html($u['nextaction']); ?></h2><p><?php echo esc_html($s['next_action'][$l] ?? $u['official']); ?></p><h2><?php echo esc_html($u['requirements']); ?></h2><p><?php echo esc_html(is_array($s['requirements'] ?? null) ? $s['requirements'][$l] : ($s['requirements'] ?? $u['unknown'])); ?></p><h2><?php echo esc_html($u['fee']); ?></h2><p><?php echo esc_html($s['fee'] ?? $u['unknown']); ?></p><?php echo self::detail_extra($s,$d);echo self::source($s);if ($l!=='de') { ?><p class="quiet"><?php echo esc_html($u['translationdraft']); ?></p><?php } ?></article><aside class="panel"><h2><?php echo esc_html($s['authority'] ?: $u['contact']); ?></h2><?php $c=array_column($d['contacts'],null,'id')[$s['contact']] ?? null;if ($c) { echo '<p><a href="'.esc_url('tel:'.preg_replace('/[^+0-9]/','',$c['phone'])).'">'.esc_html($c['phone']).'</a></p><p>'.esc_html($c['email']).'</p>';  } ?><a class="button" data-official="<?php echo esc_attr($s['id']); ?>" href="<?php echo esc_url($s['official_url']); ?>" rel="noopener"><?php echo esc_html($u['official']); ?> ↗</a><a class="button secondary" href="<?php echo esc_url(self::url('ask').'#'.$s['id']); ?>"><?php echo esc_html($u['compose']); ?></a></aside></div><?php
                } else { echo self::searchform();echo '<div class="filters">'.self::select('topic',$u['filter'],array_merge(['all'=>$u['all']],array_combine(['administration','everyday-life','health-social','education-family','jobs-business','culture-leisure'],array_map([self::class,'t'],['administration','everyday-life','health-social','education-family','jobs-business','culture-leisure'])))).'</div><div class="cards" id="directory">';foreach(self::slice($d['services']) as $s) { echo self::card($s); }echo '</div>'.self::pagination(count($d['services'])); } break;
            case 'topics':$list=array_values(array_filter($d['services'],fn($s)=>$s['topic']===$parts[1]));echo '<div class="cards">';foreach(self::slice($list) as $s) { echo self::card($s); }echo '</div>'.self::pagination(count($list));break;
            case 'places':
                ?><div class="filters"><?php echo self::select('locality',$u['locality'],self::localities()); ?></div><div class="two-columns"><section class="panel"><h2><?php echo esc_html($u['calendar']); ?></h2><div id="event-list"></div></section><section class="panel"><h2><?php echo esc_html($u['waste']); ?></h2><div id="waste-list"></div></section></div><section class="section"><h2><?php echo esc_html($u['services']); ?></h2><div class="cards"><?php foreach ($d['services'] as $s) { if ($s['locality']===$parts[1] || in_array($s['id'],['school','transport','23620'],true)) { echo self::card($s); } } ?></div></section><a href="https://www.oberriet.ch/5doerfer1gemeinde"><?php echo esc_html($u['official']); ?> ↗</a><?php break;
            case 'calendar':?><div class="filters"><?php echo self::select('locality',$u['locality'],self::localities()).self::select('period',$u['filter'],['future'=>$u['future'],'today'=>$u['today'],'week'=>$u['week'],'month'=>$u['month']]).self::select('event-type',$u['type'],['all'=>$u['all'],'culture'=>$u['culture-leisure'],'waste'=>$u['waste'],'school'=>$u['education-family']]); ?></div><div id="event-list" class="event-grid"></div><button id="ics" class="button"><?php echo esc_html($u['export']); ?></button><p><a href="https://www.oberriet.ch/anlaesseaktuelles"><?php echo esc_html($u['official']); ?> ↗</a></p><?php break;
            case 'waste':?><div class="filters"><?php echo self::select('locality',$u['locality'],self::localities()); ?></div><p class="quiet"><?php echo esc_html($u['valid']); ?> 2026 · <a href="https://www.oberriet.ch/online-schalter/101755/download">Abfallentsorgungsplan 2026 ↗</a></p><div id="waste-list" class="cards"></div><?php break;
            case 'ask':?><p><?php echo esc_html($u['sensitive']); ?></p><label class="field" for="problem"><?php echo esc_html($u['problem']); ?><textarea id="problem" rows="3" maxlength="600"></textarea></label><button class="button" id="classify"><?php echo esc_html($u['classify']); ?></button><div id="router-results" class="cards section" aria-live="polite"></div><section id="composer" class="panel" hidden><h2><?php echo esc_html($u['compose']); ?></h2><p id="recipient"></p><p class="quiet"><?php echo esc_html($u['routeconfirm']); ?></p><div class="two-columns"><label class="field" for="resident-name"><?php echo esc_html($u['name']); ?><input id="resident-name" maxlength="100"></label><label class="field" for="location"><?php echo esc_html($u['location']); ?><input id="location" maxlength="200"></label></div><label class="field" for="description"><?php echo esc_html($u['description']); ?><textarea id="description" rows="4" maxlength="3000"></textarea></label><label class="field" for="draft">E-Mail<textarea id="draft" rows="12" readonly></textarea></label><div class="actions"><button class="button" id="copy"><?php echo esc_html($u['copy']); ?></button><a class="button secondary" id="mailto"><?php echo esc_html($u['openmail']); ?></a><button id="clear" class="button secondary"><?php echo esc_html($u['clear']); ?></button></div><p id="copy-status" role="status"></p><p class="quiet"><?php echo esc_html($u['localdraft']); ?></p></section><?php break;
            case 'organizations':case 'contacts':$kind=$active==='organizations'?'organizations':'contacts';$list=$d[$kind] ?? [];if(isset($parts[1])){$list=array_values(array_filter($list,fn($r)=>$r['id']===$parts[1]));}echo '<div class="cards">';foreach(self::slice($list) as $row){echo self::entity_card($row,$kind);}echo '</div>'.self::pagination(count($list));break;
            case 'faq':echo '<div class="prose">';foreach(self::slice($d['faqs'] ?? []) as $r){echo '<details><summary>'.esc_html(is_array($r['title'])?$r['title'][$l]:$r['title']).'</summary><p>'.esc_html($r['answer'][$l] ?? $r['description_short'][$l] ?? '').'</p>'.self::source($r).'</details>';}echo '</div>'.self::pagination(count($d['faqs'] ?? []));break;
            case 'contact':echo '<div class="cards">';foreach(self::slice($d['contacts']) as $c) { ?><article class="service-card"><h2><a href="<?php echo esc_url(self::url('contacts/'.$c['id'])); ?>"><?php echo esc_html($c['title']); ?></a></h2><p><?php echo esc_html($c['phone']); ?></p><?php if(is_email($c['email'])) { ?><a href="<?php echo esc_url('mailto:'.$c['email']); ?>"><?php echo esc_html($c['email']); ?></a><?php } ?><p><a href="<?php echo esc_url($c['official_url']); ?>"><?php echo esc_html($u['official']); ?> ↗</a></p><?php echo self::source($c); ?></article><?php }echo '</div>';break;
            case 'sources':echo '<div class="prose"><p>'.esc_html($u['quality']).'</p><p>'.esc_html($u['trustlevels']).'</p></div><div class="source-table">';foreach(self::slice($d['sources']) as $s) { ?><article><span class="badge"><?php echo esc_html($s['trust_level']); ?></span><div><h2><a href="<?php echo esc_url($s['source_url']); ?>"><?php echo esc_html($s['authority']); ?> ↗</a></h2><p><?php echo esc_html($s['source_domain'].' · '.$u['checked'].' '.$s['last_checked']); ?></p><small><?php echo esc_html($s['review_status']); ?></small></div></article><?php }echo '</div>'.self::pagination(count($d['sources']));break;
            default:echo self::legal($active);break;
        }
        } }
        ?><section class="trust-strip"><strong><?php echo esc_html($u['quality']); ?></strong><span><?php echo esc_html($u['free']); ?></span><a href="<?php echo esc_url(self::url('sources')); ?>"><?php echo esc_html($u['sources']); ?> →</a></section></main><footer><div class="wrap footer-main"><a class="brand" href="<?php echo esc_url(self::url()); ?>">oberriet<span class="brand-light">hub</span></a><p><?php echo esc_html($u['disclaimer']); ?></p><nav><?php foreach(['about','contact','sources','privacy','imprint','accessibility'] as $p) { ?><a href="<?php echo esc_url(self::url($p)); ?>"><?php echo esc_html($u[$p]); ?></a><?php } ?></nav><p class="emergency"><?php echo esc_html($u['emergency']); ?>: <a href="tel:112">112</a> · <?php echo esc_html($u['police']); ?> <a href="tel:117">117</a> · <?php echo esc_html($u['fire']); ?> <a href="tel:118">118</a> · <?php echo esc_html($u['ambulance']); ?> <a href="tel:144">144</a> · Tox <a href="tel:145">145</a> <a href="https://www.hallo.sg.ch/de/beratung-kontakte/notfaelle.html"><?php echo esc_html($u['source']); ?> ↗</a></p></div></footer></div><?php return ob_get_clean();
    }
    public static function slice(array $rows): array { $page=max(1,min(10000,absint($_GET['listing_page'] ?? 1)));return array_slice($rows,($page-1)*24,24); }
    public static function pagination(int $count): string { $page=max(1,absint($_GET['listing_page'] ?? 1));$pages=(int)ceil($count/24);if($pages<=1)return ''; $h='<nav class="pagination" aria-label="'.esc_attr(self::t('pages')).'">';if($page>1)$h.='<a class="button secondary" href="'.esc_url(add_query_arg('listing_page',$page-1,self::url(self::path()))).'">← '.esc_html(self::t('previous')).'</a>'; $h.='<span>'.(int)$page.' / '.$pages.'</span>';if($page<$pages)$h.='<a class="button secondary" href="'.esc_url(add_query_arg('listing_page',$page+1,self::url(self::path()))).'">'.esc_html(self::t('next')).' →</a>';return $h.'</nav>'; }
    public static function entity_card(array $r,string $kind): string { $l=self::lang();$title=is_array($r['title'] ?? null)?$r['title'][$l]:($r['title'] ?? $r['id']);$h='<article class="service-card"><h2><a href="'.esc_url(self::url($kind.'/'.$r['id'])).'">'.esc_html($title).'</a></h2>';if(!empty($r['description_short'][$l]))$h.='<p>'.esc_html($r['description_short'][$l]).'</p>';if(!empty($r['address']))$h.='<p>'.esc_html(is_array($r['address'])?implode(', ',$r['address']):$r['address']).'</p>';if(!empty($r['phone']))$h.='<p><a href="'.esc_url('tel:'.preg_replace('/[^+0-9]/','',$r['phone'])).'">'.esc_html($r['phone']).'</a></p>';if(is_email($r['email'] ?? ''))$h.='<p><a href="'.esc_url('mailto:'.$r['email']).'">'.esc_html($r['email']).'</a></p>';if(!empty($r['official_url']))$h.='<a href="'.esc_url($r['official_url']).'">'.esc_html(self::t('official')).' ↗</a>';return $h.self::source($r).'</article>'; }
    public static function detail_extra(array $s,array $d): string { $l=self::lang();$h='';foreach(['steps'=>'steps','documents'=>'documents','processing_time'=>'processingtime','eligibility'=>'eligibility'] as $key=>$label){$v=$s[$key] ?? null;if(!$v)continue;if(is_array($v)&&isset($v[$l]))$v=$v[$l];$h.='<h2>'.esc_html(self::t($label)).'</h2>';if(is_array($v)){$h.='<ol>';foreach($v as $item){$h.='<li>'.esc_html(is_scalar($item)?(string)$item:'').'</li>';}$h.='</ol>';}else{$h.='<p>'.esc_html((string)$v).'</p>';}}$related=array_filter($d['services'],fn($r)=>$r['id']!==$s['id']&&(in_array($r['id'],$s['related_services'] ?? [],true)||$r['topic']===$s['topic']));if($related){$h.='<h2>'.esc_html(self::t('related')).'</h2><ul>';foreach(array_slice(array_values($related),0,5) as $r){$h.='<li><a href="'.esc_url(self::url('services/'.$r['id'])).'">'.esc_html($r['title'][$l]).'</a></li>';}$h.='</ul>';}return $h; }
    public static function legal(string $page): string {
        $content=json_decode(file_get_contents(OBERHUB_DIR.'/legal.json'),true);$l=self::lang();$o=get_option('oh_operator',[]);$h='<article class="prose">';
        foreach (($content[$page][$l] ?? []) as $text) { $h.='<p>'.esc_html($text).'</p>'; }
        if ($page==='imprint' || $page==='privacy') {
            if (self::operator_ready()) { $h.='<p>'.esc_html(implode(' · ',array_filter([$o['operator'],$o['organization'] ?? '',$o['responsible_person'] ?? '',$o['address'],$o['email'],$o['phone'] ?? '']))).'</p>'; }
            else { $h.='<p class="warning">'.esc_html($content['operator_missing'][$l]).'</p>'; }
        }
        if ($page==='privacy') { if (!empty($o['hosting_provider'])) { $h.='<p>Hosting: '.esc_html($o['hosting_provider'].' · '.$o['hosting_country']).'</p>'; }$h.='<p><a href="https://www.fedlex.admin.ch/eli/cc/2022/491/de">DSG SR 235.1 ↗</a> · <a href="https://www.edoeb.admin.ch/de/das-neue-datenschutzgesetz-aus-sicht-des-edob">EDÖB ↗</a></p>'; }
        if ($page==='imprint') { $h.='<p><a href="https://www.fedlex.admin.ch/eli/cc/2015/613/de">WSchG SR 232.21 ↗</a> · <a href="https://www.ige.ch/de/etwas-schuetzen/marken/vor-der-anmeldung/schutzvoraussetzungen/eintragungshindernisse/geschuetzte-oeffentliche-zeichen">IGE ↗</a></p>'; }
        return $h.'</article>';
    }
}
