import json,pathlib,hashlib
R=pathlib.Path(__file__).resolve().parents[1];d=json.loads((R/'data/seed.json').read_text());D='2026-10-01';L=['de','en','ru','uk']
def source(url,authority,trust='A',ttl=30,scope='page'):
 sid='s-'+hashlib.sha256(url.encode()).hexdigest()[:12]
 s=next((s for s in d['sources'] if s['source_id']==sid),None)
 if not s:
  s={'source_id':sid,'source_url':url,'source_domain':url.split('/')[2],'source_type':'official-web','authority':authority,'license_or_reuse_note':'Original factual summary only; no copied images or protected prose.','last_checked':D,'last_changed':None,'http_status':None,'content_hash':'','review_status':'checked','trust_level':trust,'ttl_days':ttl,'verification_scope':scope};d['sources'].append(s)
 return sid
for s in d['services']:s['verification_scope']='routing-metadata' if s['source_id'] in [x['source_id'] for x in d['sources'] if x['source_url'].endswith('/dienstleistungen')] else 'page';s['next_action']={l:{'de':'Offizielle Seite öffnen oder die angegebene Stelle kontaktieren.','en':'Open the official page or contact the listed office.','ru':'Откройте официальную страницу или свяжитесь с указанной службой.','uk':'Відкрийте офіційну сторінку або зв’яжіться із зазначеною службою.'}[l] for l in L}
for s in d['sources']:s.setdefault('verification_scope','page' if s['http_status']==200 else 'public-page/search-verification')
def contact(cid,title,phone,email,url,address,locality='all',trust='B'):
 d['contacts'].append({'id':cid,'title':title,'phone':phone,'email':email,'address':address,'official_url':url,'source_url':url,'source_id':source(url,title,trust),'source_checked_at':D,'locality':locality,'trust_level':trust,'status':'checked'})
contact('school-ekmo','Schulverwaltung Oberriet','+41 71 763 62 00','schulverwaltung@orschulen.ch','https://www.orschulen.ch/kontakt-227.html','Staatsstrasse 135, 9463 Oberriet')
contact('school-montlingen','Primarschule Montlingen','+41 71 763 62 20','','https://www.orschulen.ch/kontakt-492.html','Bergliweg 8, 9462 Montlingen','montlingen')
contact('school-kriessern','Primarschule Kriessern / Rheinau','+41 71 763 65 40','','https://www.orschulen.ch/lageplan-443.html','Kirchdorfstrasse 12, 9451 Kriessern','kriessern')
contact('music','Musikschule Oberrheintal','+41 71 755 19 75','info@msor.ch','https://msor.ch/kontakt/','Churerstrasse 51, 9450 Altstätten')
contact('hospital-grabs','HOCH Health Ostschweiz / Grabs','+41 81 772 51 11','kontakt.grabs@h-och.ch','https://www.h-och.ch/ueber-uns/standorte/grabs/','Spitalstrasse 44, 9472 Grabs')
def add(sid,titles,summary,url,topic,authority,cid='gemeinde',locality='all',trust='A',aliases=[]):
 row={'id':sid,'slug':sid,'title':dict(zip(L,titles)),'description_short':dict(zip(L,summary)),'description_full':dict(zip(L,summary)),'topic':topic,'subtopic':'','locality':locality,'authority':authority,'contact':cid,'official_url':url,'source_url':url,'source_id':source(url,authority,trust),'source_checked_at':D,'source_trust_level':trust,'status':'checked','translation_status':dict.fromkeys(L[1:],'draft'),'keywords':' '.join(titles),'synonyms':aliases,'verification_scope':'page','fee':None,'requirements':None,'eligibility':None,'documents':None,'processing_time':None,'online_available':None,'next_action':dict(zip(L,['Offizielle Seite öffnen oder die Stelle kontaktieren.','Open the official page or contact the office.','Откройте официальный сайт или свяжитесь со службой.','Відкрийте офіційний сайт або зв’яжіться зі службою.']))};d['services'].append(row)
 return row
s=next(s for s in d['services'] if s['id']=='school');s.update(contact='school-ekmo',authority='Schulverwaltung Oberriet',official_url='https://www.orschulen.ch/primarschule-ekmo/e.html',source_url='https://www.orschulen.ch/primarschule-ekmo/e.html',source_id=source('https://www.orschulen.ch/primarschule-ekmo/e.html','Schulverwaltung Oberriet','B'),source_trust_level='B');s['description_short']=dict(zip(L,['Für einen Zuzug in die Primarschulen EKMO steht der offizielle E-Zuzug bereit. Schule und Adresse mit der Schulverwaltung bestätigen; Oberstufe und Kriessern separat abklären.','Use the official E-Zuzug form for EKMO primary schools. Confirm school and address with Schulverwaltung; check secondary school and Kriessern separately.','Для начальных школ EKMO есть официальный E-Zuzug. Уточните школу по адресу в Schulverwaltung; старшие классы и Kriessern уточняются отдельно.','Для початкових шкіл EKMO є офіційний E-Zuzug. Уточніть школу за адресою в Schulverwaltung; старші класи та Kriessern уточнюються окремо.']));s['description_full']=s['description_short'].copy()
for place,address,url,cid in [('oberriet','Kirchstrasse 4, 9463 Oberriet','https://www.orschulen.ch/kontakt-227.html','school-ekmo'),('montlingen','Bergliweg 8, 9462 Montlingen','https://www.orschulen.ch/kontakt-492.html','school-montlingen'),('kriessern','Kirchdorfstrasse 12, 9451 Kriessern','https://www.orschulen.ch/lageplan-443.html','school-kriessern'),('eichenwies','Alvierstrasse 1, 9463 Oberriet','https://www.orschulen.ch/dazolino-fruehe-foerderung-in-sprache-und-spiel.html','school-ekmo'),('kobelwald','Hard / Bergstrasse 37, 9463 Oberriet','https://www.orschulen.ch/kontakt-227.html','school-ekmo')]:
 name=place.capitalize();add('school-'+place,[f'Primarschule {name}',f'{name} primary school',f'Начальная школа {name}',f'Початкова школа {name}'],[f'Schulstandort: {address}. Anmeldung und Einteilung mit der Schule bestätigen.',f'School location: {address}. Confirm registration and school assignment with the school.',f'Адрес школы: {address}. Регистрацию и распределение уточните в школе.',f'Адреса школи: {address}. Реєстрацію та розподіл уточніть у школі.'],url,'education-family',f'Primarschule {name}',cid,place,'B')
add('childcare',['Tagesstrukturen EKMO','EKMO day care','Дневной уход EKMO','Денний догляд EKMO'],['Die offiziellen Tagesstrukturen EKMO informieren über Betreuung, Anmeldung und Tarife. Verfügbarkeit direkt bestätigen.','Official EKMO day-care information covers care, applications and fees. Confirm availability directly.','На сайте Tagesstrukturen EKMO указаны уход, регистрация и тарифы. Наличие мест уточняйте напрямую.','На сайті Tagesstrukturen EKMO зазначені догляд, реєстрація й тарифи. Наявність місць уточнюйте напряму.'],'https://www.orschulen.ch/tagesstrukturen-ekmo.html','education-family','Schulverwaltung Oberriet','school-ekmo',trust='B',aliases=['daycare','childcare','betreuung','продлёнка','група продовженого дня'])
add('school-holidays',['Schulferien 2026: OZ / Montlingen','2026 school holidays: OZ / Montlingen','Каникулы 2026: OZ / Montlingen','Канікули 2026: OZ / Montlingen'],['Veröffentlicht: Herbstferien 26.09.–18.10.2026; Weihnachtsferien 19.12.2026–03.01.2027. Geltung: Oberstufe und Primarschule Montlingen; andere Schulen separat prüfen.','Published autumn holidays: 26 September–18 October 2026; Christmas: 19 December 2026–3 January 2027. Scope: secondary schools and Montlingen primary; check other schools separately.','Опубликованы осенние каникулы 26.09–18.10.2026 и рождественские 19.12.2026–03.01.2027 для Oberstufe и начальной школы Montlingen. Другие школы проверяйте отдельно.','Опубліковано осінні канікули 26.09–18.10.2026 та різдвяні 19.12.2026–03.01.2027 для Oberstufe й початкової школи Montlingen. Інші школи перевіряйте окремо.'],'https://www.orschulen.ch/ferienplan.html','education-family','Oberstufenschulen Oberriet','school-ekmo',trust='B',aliases=['schulferien','school holidays','каникулы','канікули'])
add('music-school',['Musikschule Oberrheintal','Oberrheintal music school','Музыкальная школа Oberrheintal','Музична школа Oberrheintal'],['Musikunterricht und Anmeldung direkt bei der Musikschule abklären. Das Sekretariat ist in Altstätten.','Ask the music school about lessons and registration. Its office is in Altstätten.','Уроки и регистрацию уточняйте в музыкальной школе; секретариат находится в Altstätten.','Уроки й реєстрацію уточнюйте в музичній школі; секретаріат розташований в Altstätten.'],'https://msor.ch/kontakt/','education-family','Musikschule Oberrheintal','music',trust='B',aliases=['musikunterricht','music lessons','музыка','музика'])
add('health-emergency',['Medizinischer Notfall / Spital Grabs','Medical emergency / Grabs hospital','Медицинская экстренная помощь / Grabs','Екстрена медична допомога / Grabs'],['Bei akuter Lebensgefahr 144 wählen. Für nicht akute Spitalinformationen den offiziellen HOCH-Standort Grabs kontaktieren. Keine medizinische Diagnose durch diesen Hub.','Call 144 for an immediate medical emergency. For non-emergency hospital information contact the official HOCH Grabs location. This Hub does not provide diagnoses.','При угрозе жизни звоните 144. По неэкстренным вопросам больницы обращайтесь в HOCH Grabs. Hub не ставит диагнозы.','За загрози життю телефонуйте 144. Із неекстрених питань лікарні звертайтеся в HOCH Grabs. Hub не встановлює діагнози.'],'https://www.h-och.ch/notfall/','health-social','HOCH Health Ostschweiz','hospital-grabs',trust='B',aliases=['hospital','medical emergency','spital','больница','лікарня','arzt','врач','лікар'])
add('crystal-cave',['Kristallhöhle Kobelwald','Kobelwald crystal cave','Кристальная пещера Kobelwald','Кришталева печера Kobelwald'],['Die Gemeinde führt die Kristallhöhle als Sehenswürdigkeit bei Kobelwald. Öffnungszeiten und Besuchsvoraussetzungen beim Betreiber prüfen.','The municipality lists the crystal cave near Kobelwald as a sight. Check current opening times and visit conditions with the operator.','Община включает кристальную пещеру у Kobelwald в список достопримечательностей. Условия посещения и часы уточняйте у оператора.','Громада включає кришталеву печеру біля Kobelwald до пам’яток. Умови відвідування й години уточнюйте в оператора.'],'https://www.oberriet.ch/sehenswuerdigkeiten/7473','culture-leisure','Politische Gemeinde Oberriet',locality='kobelwald',aliases=['höhle','cave','пещера','печера'])
add('blatten',['Burgruine Blatten','Blatten castle ruins','Руины замка Blatten','Руїни замку Blatten'],['Offizieller Sehenswürdigkeiten-Eintrag: Burgruine Blatten, Schlossweg, Oberriet. Zugang und aktuelle Hinweise im Original prüfen.','Official sight listing: Blatten castle ruins, Schlossweg, Oberriet. Check access and current notices on the original page.','Официальная достопримечательность: руины Blatten, Schlossweg, Oberriet. Доступ и актуальные указания проверяйте в оригинале.','Офіційна пам’ятка: руїни Blatten, Schlossweg, Oberriet. Доступ і актуальні вказівки перевіряйте в оригіналі.'],'https://www.oberriet.ch/sehenswuerdigkeiten/7474','culture-leisure','Politische Gemeinde Oberriet',locality='oberriet',aliases=['burgruine','castle ruins','замок','замку'])
add('museum',['Museum Rothus','Rothus museum','Музей Rothus','Музей Rothus'],['Das Museum Rothus ist im offiziellen Sehenswürdigkeiten-Verzeichnis eingetragen. Aktuelle Ausstellungen und Öffnungszeiten im Original prüfen.','Rothus museum appears in the official sights directory. Check current exhibitions and opening times on the original page.','Музей Rothus указан в официальном списке достопримечательностей. Выставки и часы проверяйте в оригинале.','Музей Rothus зазначений в офіційному переліку пам’яток. Виставки й години перевіряйте в оригіналі.'],'https://www.oberriet.ch/sehenswuerdigkeiten/7482','culture-leisure','Politische Gemeinde Oberriet',locality='oberriet',aliases=['museum','музей'])
add('sbb-daycard',['SBB Spartageskarte','SBB Saver Day Pass','Дневной проездной SBB','Денний проїзний SBB'],['Die SBB bietet eine Spartageskarte an. Preis und Verfügbarkeit sind dynamisch: direkt bei SBB prüfen. Keine Zusage eines Gemeindeverkaufs.','SBB offers a Saver Day Pass. Prices and availability change; check directly with SBB. Municipal sale is not promised.','У SBB есть дневной проездной со скидкой. Цены и наличие меняются: проверяйте в SBB. Продажа общиной не подтверждается.','У SBB є денний проїзний зі знижкою. Ціни й наявність змінюються: перевіряйте в SBB. Продаж громадою не підтверджується.'],'https://www.sbb.ch/de/angebote/spartageskarte','everyday-life','SBB',trust='B',aliases=['tageskarte','day pass','дневной проездной','денний проїзний'])
for sid,aliases in [('24176',['garbage','waste','abfall','kehricht','karton','papier','сміття','сміття вивіз','мусор','вывоз мусора','бумага','картон','karton montlingen']),('23986',['tax return','taxes','налоговая декларация','податкова декларація']),('lighting',['фонарь сломан','broken street light','ліхтар не працює'])]:
 s=next(s for s in d['services'] if s['id']==sid);s['synonyms']=list(dict.fromkeys(s['synonyms']+aliases))
# Official waste plan identifies paper collection for the mountain area; Kobelwald locality source confirms mountain-area membership.
for w in d['waste']:
 w['district']={'kobelwald':'Berggebiet / Holzrhode'}
 if w['id']=='papier':w['dates']['kobelwald']=['2026-11-02']
# School events are scoped to Montlingen; other schools are not inferred.
for eid,titles,start,end in [('autumn-montlingen',['Herbstferien Primarschule Montlingen','Montlingen primary autumn holidays','Осенние каникулы начальной школы Montlingen','Осінні канікули початкової школи Montlingen'],'2026-09-26','2026-10-18'),('christmas-montlingen',['Weihnachtsferien Primarschule Montlingen','Montlingen primary Christmas holidays','Рождественские каникулы начальной школы Montlingen','Різдвяні канікули початкової школи Montlingen'],'2026-12-19','2027-01-03')]:
 url='https://www.orschulen.ch/ferienplan-se-montlingen.html';d['events'].append({'id':eid,'title':dict(zip(L,titles)),'description':dict(zip(L,['Geltung nur für diese Schule; andere Schulen prüfen.','Applies to this school only; check other schools separately.','Только для этой школы; другие проверяйте отдельно.','Лише для цієї школи; інші перевіряйте окремо.'])),'date':start,'end_date':end,'locality':'montlingen','type':'school','location':'Primarschule Montlingen','source_url':url,'official_url':url,'source_id':source(url,'Primarschule Montlingen','B',7),'source_checked_at':D})
for sid in ['childcare','school-holidays','music-school','health-emergency','crystal-cave','blatten','museum','sbb-daycard']:
 s=next(s for s in d['services'] if s['id']==sid);d['intents'].append({'id':sid,'phrases':list(s['title'].values())+s['synonyms']})
next(s for s in d['services'] if s['id']=='rav')['contact']='contact-3'
next(e for e in d['events'] if e['id']=='marvin26').pop('start_time',None)
# All contact records have explicit provenance URLs.
for c in d['contacts']:c.setdefault('source_url',c['official_url'])
# Record legal and dataset provenance without turning it into service eligibility.
for url,name in [('https://www.fedlex.admin.ch/eli/cc/2022/491/de','Bundesrecht: DSG'),('https://www.fedlex.admin.ch/eli/cc/2015/613/de','Bundesrecht: WSchG'),('https://www.gesetzessammlung.sg.ch/app/de/texts_of_law/142.1','Kanton St.Gallen: Datenschutzgesetz'),('https://www.ige.ch/de/etwas-schuetzen/marken/vor-der-anmeldung/schutzvoraussetzungen/eintragungshindernisse/geschuetzte-oeffentliche-zeichen','IGE: Öffentliche Zeichen'),('https://daten.sg.ch/explore/dataset/stationsbasierte-shared-mobility-angebote-im-kanton-stgallen/api/','OpenData St.Gallen: documented API')]:source(url,name,ttl=90)
for p in [R/'data/seed.json',R/'wp-content/plugins/oberhub-core/seed.json']:p.write_text(json.dumps(d,ensure_ascii=False,indent=2))
(R/'data/sources.json').write_text(json.dumps(d['sources'],ensure_ascii=False,indent=2));(R/'data/intents.json').write_text(json.dumps(d['intents'],ensure_ascii=False,indent=2))
print({k:len(d[k]) for k in ['services','contacts','events','waste','sources','intents']})
